### ISSUE TITLE
CRAN requested doc updates

### ISSUE THREAD

**Issue by skyebend** [statnet/tsna#12]
Dear maintainer,

Please see the problems shown on
[<https://cran.r-project.org/web/checks/check_results_tsna.html>](https://cran.r-project.org/web/checks/check_results_tsna.html).

Please correct before 2025-05-13 to safely retain your package on CRAN.

```
Check Details

Version: 0.3.5
Check: Rd cross-references
Result: NOTE
  Found the following Rd file(s) with Rd \link{} targets missing package
  anchors:
    density.Rd: networkDynamic
    durations.Rd: net.obs.period, as.data.frame.networkDynamic,
      get.vertex.activity
    incidence.Rd: networkDynamic
    plotpath.Rd: plot.network
    tDegree.Rd: networkDynamic
    tErgmStats.Rd: networkDynamic, network.collapse
    tSnaStats.Rd: network.collapse
    tiedDuration.Rd: networkDynamic
    timeProjectedNetwork.Rd: networkDynamic, network.collapse,
      get.networks, network
  Please provide package anchors for all Rd \link{} targets not in the
  package itself and the base packages.
Flavors: [r-devel-linux-x86_64-debian-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/tsna-00check.html), [r-devel-linux-x86_64-debian-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/tsna-00check.html), [r-patched-linux-x86_64](https://www.r-project.org/nosvn/R.check/r-patched-linux-x86_64/tsna-00check.html), [r-release-linux-x86_64](https://www.r-project.org/nosvn/R.check/r-release-linux-x86_64/tsna-00check.html)
```
